import "./src/css/all/animate.css"
import "./src/css/frontend/icomoon.css"
import "./src/css/all/bootstrap.css"
import "./src/css/frontend/magnific-popup.css"
import "./src/css/frontend/flexslider.css"
import "./src/css/frontend/owl.carousel.min.css"
import "./src/css/frontend/owl.theme.default.min.css"
import "./src/css/frontend/vs2015.css"
import "./src/font/flaticon/font/flaticon.css"
import "./src/css/frontend/style.css"
// import "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900"